"""
/***************************************************************************
 RasterTools
                                 A QGIS plugin
 This plugin provides a raster calculator and delivered cost calculator.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-31
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Tim Van Driel
        email                : timothy.vandriel@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


class RasterCalcError(Exception):
    pass


class LayerNotFoundError(RasterCalcError):
    pass


class InvalidExpressionError(RasterCalcError):
    pass


class RasterSaveError(RasterCalcError):
    pass


class RasterToolsUnavailableError(RasterCalcError):
    pass


class BandMismatchError(RasterCalcError):
    pass


class RasterExtentError(RasterCalcError):
    pass
